Meteor.startup(function () {
  if(Markers.find().count() === 0){
    let marker = [
// 1
      {
        lat: 12.927608,
        lng: 100.877081,
        thumbnailUrl: 'https://copy.com/wkJQvBrERixvr63T',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'pattaya1',
        contentUrl : [
          'https://copy.com/wkJQvBrERixvr63T',
        	'https://copy.com/WP8fAYiaRigeH8Mr',
        	'https://copy.com/2uzfsZzBII8zkgQI',
        	'https://copy.com/BDZHVW4lMtOZTNRA',
        	'https://copy.com/jrUCCeS1UqHS3QTS',
        	'https://copy.com/XT8HXys0PsckW7w4',
        	'https://copy.com/pX63wEF6BTEBDWFi',
        	'https://copy.com/xwR8VPY1otMb3Vc8',
        	'https://copy.com/9YzBtCg8nfNXX7MO',
        	'https://copy.com/JYghl4nAZniLeYK7',
        	'https://copy.com/PeNfZL92I1w10NIz',
        	'https://copy.com/ibG8RQcJqXqGnchi',
        	'https://copy.com/CTHJUqiPfQkwXEDZ',
        	'https://copy.com/CS3nugJEE2n4I8Se',
        	'https://copy.com/HXCaM9NMjTvQg8Jj',
        	'https://copy.com/PHdpZteXg2DM4NCZ',
        	'https://copy.com/eHYFLB1jRj4KAyOl',
        	'https://copy.com/1UsMIfkbYzmpfu7W',
        	'https://copy.com/eBiflUKNnJpbZfqv',
        	'https://copy.com/mR8G4kikT1sByoIs',
        ]
      },
// 2
      {
        lat: 12.923181,
        lng: 100.868139,
        thumbnailUrl: 'https://copy.com/b4Pm6YJViuKakwI9',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'pattaya2',
        contentUrl : [
          'https://copy.com/b4Pm6YJViuKakwI9',
        	'https://copy.com/pbjbTskEoStd2KyM',
        	'https://copy.com/ojz9nZzxQqNvzjOn',
        	'https://copy.com/1ER9xMZR4ALDRddx',
        	'https://copy.com/LlC3NgNQmKW0cQ0G',
        	'https://copy.com/3Sf0qDLjSqjZIWJu',
        	'https://copy.com/8bq9Ub7P41FwiCiE',
        	'https://copy.com/hHI87QEz1u3rN9LO',
        	'https://copy.com/GcTbgvyhYxTcPlBs',
        	'https://copy.com/f8w8GJZGbZJnRnis',
        	'https://copy.com/Dx9koIMv1YrXoMt3',
        	'https://copy.com/u2YAyMSu84lhmgIi',
        	'https://copy.com/HypZSwylNaLdFNku',
        	'https://copy.com/t8GPr8KDWXD6kI3t',
        	'https://copy.com/LgbEeymQQBc47Kws',

        ]
      },
// 3
      {
        lat: 12.949301,
        lng: 100.884705,
        thumbnailUrl:'https://copy.com/2mlMFqPLwcZB8EUQ',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'pattaya3',
        contentUrl : [
          'https://copy.com/2mlMFqPLwcZB8EUQ',
        	'https://copy.com/1bLtnjy33yon8ZWa',
        	'https://copy.com/6xVrsPeIERUe09sf',
        	'https://copy.com/nPXdYV9R7JFZDxPJ',
        	'https://copy.com/SiglMH6DEIXejHtQ',
        	'https://copy.com/LnFTyYGaOySjAYi9',
        	'https://copy.com/QK3T19r0xtoAKwca',
        	'https://copy.com/8hDgS1yqnCuttOnu',
        	'https://copy.com/PR6gXbnmNZkKE6RA',
        	'https://copy.com/dlibnYKcjLyIweek',
        	'https://copy.com/89uNwBhGa7XlRsdx',
        	'https://copy.com/D8FGAR3g4Sh93B0V',
        	'https://copy.com/BrKgpIK0G14tHAaA',
        	'https://copy.com/sUREfDTIddZPwqZo',
        	'https://copy.com/hpD3a0ucJZQRRMUC',
        	'https://copy.com/zOszcykcxUArJ0VD',
        	'https://copy.com/Gz41M4AaUElXAQTp',
        	'https://copy.com/6pZSEjjHBnmucVeo',
        	'https://copy.com/013KcChMRHpoye0d',
        	'https://copy.com/bnlkasOlFaWUpDZf',
        	'https://copy.com/wZyoTujdW1Gohl3s',
        	'https://copy.com/7EPlSZcHNe2zgKvr',
        	'https://copy.com/9pjQmnEWuVvNzBhJ',
        	'https://copy.com/Fa9uIMxJgS0BizVu',
        	'https://copy.com/lLeYpxLJTv3qsOTs',
        ]
      },
// 4
      {
        lat: 19.359228,
        lng: 98.437269,
        thumbnailUrl:'https://copy.com/mVW4FVfyFR3T8IAv',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Pai',
        contentUrl : [
          'https://copy.com/mVW4FVfyFR3T8IAv',
        	'https://copy.com/fITDlWqacJMjeg9h',
        	'https://copy.com/By4ExpHQFhCIfxkC',
        	'https://copy.com/zFA1BKO7NtJ4Dzxy',
        	'https://copy.com/j8eC8jXAzmWITadG',
        	'https://copy.com/K0v0ZhawbYlH8pnf',
        	'https://copy.com/ivGIWnQVOUsdNkBA',
        	'https://copy.com/wHS4dCS8vi27AVNT',
        	'https://copy.com/hXiKO2RTKWL3Y64j',
        	'https://copy.com/uRiWD1jb9Gj1cq3C',
        	'https://copy.com/GMPlJFllqj4qPk8B',
        	'https://copy.com/uoFjKHgB7UQL4F3S',
        	'https://copy.com/v2WcyB1V9tmdbQYz',
        	'https://copy.com/0WoXBVei9DcgljPz',
        	'https://copy.com/ySn06Q6wnJHzg3LM',
        ]
      },
// 5
      {
        lat: 41.242726,
        lng: 16.502065,
        thumbnailUrl:'https://copy.com/Y2KWTsiARWL6soqY',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Italy1',
        contentUrl : [
          'https://copy.com/Y2KWTsiARWL6soqY',
        	'https://copy.com/ovRWjITHL01MbxvJ',
        	'https://copy.com/KSPlxnP48G7nTVi3',
        	'https://copy.com/vNdXvE1CGjx9JRgH',
        	'https://copy.com/oSBu2HxsSU0unjMC',
        	'https://copy.com/bxjC6GnZua0g42FI',
        	'https://copy.com/ERwSmIA1VQqOcRQg',
        	'https://copy.com/4LQryIFBtqsZnlaQ',
        	'https://copy.com/TrgqWFvN6vvp3vyr',
        	'https://copy.com/4WOIoccrDXXWaxvF',
        	'https://copy.com/z4Y1jJ1tscE8CMRe',
        	'https://copy.com/cBm9ursw2ENjsT8Q',
        	'https://copy.com/sdpssf6UIyUkhCkC',
        	'https://copy.com/UELZO01twlg7iSPE',
        	'https://copy.com/iLV9PYt87O6DIFtD',
        	'https://copy.com/CX2wK24gRhmvNDwv',
        ]
      },
// 6
      {
        lat: 41.252153,
        lng: 16.474085,
        thumbnailUrl:'https://copy.com/XEnrRR94neKRSQfF',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Italy2',
        contentUrl : [
          'https://copy.com/aQ1zyASzFhQYlBY4',
        	'https://copy.com/hiIGLYUmdcfnvYmo',
        	'https://copy.com/DvbY2Bq6dQ0dpHgO',
        	'https://copy.com/EY1s24J7hmM8bKd7',
        	'https://copy.com/XEnrRR94neKRSQfF',
        	'https://copy.com/7lC2AAuAw9DTOLUs',
        	'https://copy.com/fD099rszb3dG1JGQ',
        	'https://copy.com/7gxHyQZdTMFhEafy',
        	'https://copy.com/mdx6ptLTPZRurqRX',
        	'https://copy.com/NfknDlfEMta4TJKQ',
        	'https://copy.com/ur7gGIVfLBRUb88s',
        	'https://copy.com/AIxiJPcpg3620rWK',
        	'https://copy.com/D4H1gwjyUEd3xYn8',
        	'https://copy.com/2MkPzs6UIHXvMSTR',
        	'https://copy.com/Rwse4kqIlsD29ULZ',
        	'https://copy.com/MoLW0eDNXSfjbo4N',
        	'https://copy.com/wf9Bgtvcw7ZBj9zD',
        	'https://copy.com/Uikq4nWRCZ1LnVez',
        	'https://copy.com/1qD9jeYfr6RFeBNU',
        	'https://copy.com/FU3Y4LOHRlDBeBra',
        	'https://copy.com/J8TCwjjUkkbFy7tI',
        	'https://copy.com/3lzVzWr6YsJNHBOH',
        	'https://copy.com/BzwupJOPnhGhgchu',
        	'https://copy.com/oEXGvRbX7Le6deuW',
        	'https://copy.com/wgPPQt0yaVICWuOW',
        	'https://copy.com/Ibfuo3I337DTmbqz',
        ]
      },
// 7
      {
        lat: 18.787747,
        lng: 98.993128,
        thumbnailUrl:'https://copy.com/tN6j8OporrTDuIGm',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Thailand-TG1',
        contentUrl : [
          'https://copy.com/tN6j8OporrTDuIGm',
        	'https://copy.com/umzPcQqgjJdukSec',
        	'https://copy.com/zHVMsaS9M8rRLszl',
        	'https://copy.com/i6keexdleVm47Rpy',
        	'https://copy.com/JbbPtURfX6kMX0qL',
        	'https://copy.com/YTI2OZRJntdCG8Mm',
        	'https://copy.com/87eidijYYniH6WG6',
        	'https://copy.com/v0XcILtXZ12Ful2A',
        	'https://copy.com/6H7lRJnDCyvohL0Z',
        	'https://copy.com/T0uRopQMAt7O7DeD',
        	'https://copy.com/KK1Ab4cpflxwEzv8',
        	'https://copy.com/rhynICnqWYrav2FZ',
        	'https://copy.com/kczYUmjS2Nmrp4IC',
        	'https://copy.com/iY2CWtUNzVLngm3u',
        	'https://copy.com/jGxqgyMIzjSScZAa',
        	'https://copy.com/76HTe4Fc9E99egIY',
        	'https://copy.com/vafzkW0YfOPYRWWl',
        	'https://copy.com/CKxkwTh9cYfEm0e4',
        	'https://copy.com/wNuCCpvF3CapBTvc',
        	'https://copy.com/q1GpNPggBYo0uqeS',
        	'https://copy.com/7SqlyRz9fsPidXuC',
        	'https://copy.com/ssEcBHftf4MxeQCn',
        	'https://copy.com/IU1mJsZv0mOW2KxM',
        	'https://copy.com/tqsUrsc16yA9DtiH',
        ]
      },
// 8
      {
        lat: 18.939656,
        lng: 98.944244,
        thumbnailUrl:'https://copy.com/qVaTcXLhRllZvnWC',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Thailand-TG2',
        contentUrl : [
          'https://copy.com/qVaTcXLhRllZvnWC',
        	'https://copy.com/0adRVhMq9fcyBh9b',
        	'https://copy.com/CjKDTO4zauTih3Cb',
        	'https://copy.com/i34ppMJfYCk1MNYn',
        	'https://copy.com/Y7tKJFxe9P1rVj0F',
        	'https://copy.com/SScGahI1DWYveDXA',
        	'https://copy.com/a7jrb48yCHNMI4Oh',
        	'https://copy.com/PTIsLtxFADExwZ30',
        	'https://copy.com/sJNHzwgNgGTimHQ7',
        	'https://copy.com/ereH4g7U3ylDBYRO',
        	'https://copy.com/8eewbZuFpc1KvQyn',
        	'https://copy.com/pAmYgGbrtqPpTiUk',
        	'https://copy.com/zDnrjW3KRYSbSzQV',
        	'https://copy.com/IjfGaJErXM0iurk6',
        	'https://copy.com/g1lA7lmhLVUmppib',
        	'https://copy.com/Kkz3Rwp39jndrGsH',
        	'https://copy.com/sMhwPiQlw0VhcOmE',
        	'https://copy.com/TM10Na371D2zCpGF',
        	'https://copy.com/VlfxCWFdpsFwMroS',
        	'https://copy.com/c0vt3RcMddJb28cG',
        	'https://copy.com/tY3Gdw1SOnVjlMHq',
        ]
      },
// 9
      {
        lat: 18.624367,
        lng: 98.977203,
        thumbnailUrl:'https://copy.com/CjKDTO4zauTih3Cb',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Thailand-TG3',
        contentUrl : [
          'https://copy.com/qVaTcXLhRllZvnWC',
        	'https://copy.com/0adRVhMq9fcyBh9b',
        	'https://copy.com/CjKDTO4zauTih3Cb',
        	'https://copy.com/i34ppMJfYCk1MNYn',
        	'https://copy.com/Y7tKJFxe9P1rVj0F',
        	'https://copy.com/SScGahI1DWYveDXA',
        	'https://copy.com/PTIsLtxFADExwZ30',
        	'https://copy.com/sJNHzwgNgGTimHQ7',
        	'https://copy.com/ereH4g7U3ylDBYRO',
        	'https://copy.com/8eewbZuFpc1KvQyn',
        	'https://copy.com/pAmYgGbrtqPpTiUk',
        	'https://copy.com/zDnrjW3KRYSbSzQV',
        	'https://copy.com/IjfGaJErXM0iurk6',
        	'https://copy.com/g1lA7lmhLVUmppib',
        	'https://copy.com/Kkz3Rwp39jndrGsH',
        	'https://copy.com/sMhwPiQlw0VhcOmE',
        	'https://copy.com/TM10Na371D2zCpGF',
        	'https://copy.com/VlfxCWFdpsFwMroS',
        	'https://copy.com/c0vt3RcMddJb28cG',
        	'https://copy.com/tY3Gdw1SOnVjlMHq',
        ]
      },
// 10
      {
        lat: 24.880095,
        lng: 102.832892,
        thumbnailUrl: 'https://copy.com/eG6PsCttmDoOxZaw',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Kunming1',
        contentUrl : [
          'https://copy.com/eG6PsCttmDoOxZaw',
        	'https://copy.com/eYYRjcVUQG10N73p',
        	'https://copy.com/jNtNqVnaHzcVISg2',
        	'https://copy.com/d6csHfswEBPXkGcM',
        	'https://copy.com/sjLHKZVlK8nSbjpW',
        	'https://copy.com/LCanxtvZr14Ty31N',
        	'https://copy.com/qdEY84O83paBXGJg',
        	'https://copy.com/SKIZsfGwjdNUlzHY',
        	'https://copy.com/RjEKQE1tYPq6qJzG',
        	'https://copy.com/zBQRk2JBqzlAdIym',
        	'https://copy.com/bivZyFiI7B2w6bxO',
        	'https://copy.com/wTvABoPAHsV7kqAV',
        	'https://copy.com/qM1zkSjiV7RNSspD',
        	'https://copy.com/P9ZSUgwMFHwOPjMy',
        	'https://copy.com/NrRzLjiE2beo4LKF',
        	'https://copy.com/KdWpNXvvcvJCaIIc',
        	'https://copy.com/Zll2WDwPqWcY8ZCR',
        ]
      },
      // 11
      {
        lat: 24.904402,
        lng: 102.817440,
        thumbnailUrl:'https://copy.com/jMhehCrFqO32F1VV',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Kunming2',
        contentUrl : [
          'https://copy.com/jMhehCrFqO32F1VV',
        	'https://copy.com/pGPM6kSsCr0JWBa1',
        	'https://copy.com/VVClxNMnsjtnf2OW',
        	'https://copy.com/lUhgez1cU12zd9vc',
        	'https://copy.com/Xpmy7DshPHIJZQ4m',
        	'https://copy.com/1QDVmkx4seESLxHM',
        	'https://copy.com/hlPVWs6zlhumMCzc',
        	'https://copy.com/oCtxkf9rPiUpdeCl',
        	'https://copy.com/2tmci0JgYoLK9Vbx',
        	'https://copy.com/Dfp0Wv1yQ4KJCCax',
        	'https://copy.com/SXnvBfxNTCQWyfCM',
        	'https://copy.com/M1zg24P3Nt7EfK7s',
        	'https://copy.com/v7vAESoJOKcBnA6L',
        	'https://copy.com/JQxwtveLepwgTCjT',
        	'https://copy.com/17uhh2FjPSOljqu4',
        	'https://copy.com/LOztpAjVDXSkKrVO',
        	'https://copy.com/mRoFpuHwOwOTSJXL',
        	'https://copy.com/DDG7u2pNuKexF3gE',
        	'https://copy.com/ICpu8TE9cbZCA9AN',
        	'https://copy.com/4FOfZ8IznspGXanX',
        	'https://copy.com/74eRIMJnyvHzG3wS',
        ]
      },
      // 12
      {
        lat: 31.230416,
        lng: 121.473701,
        thumbnailUrl:'https://copy.com/aAVFL3LYUx6F2uMO',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Shanghai1',
        contentUrl : [
          'https://copy.com/pw7fKFrguaUz1EUj',
        	'https://copy.com/bOpsvwPvC0LuCtFw',
        	'https://copy.com/pKfpbuGeexfFsJWw',
        	'https://copy.com/NIBurISvdcSXEUK9',
        	'https://copy.com/TI39DWKFoYRuRrAv',
        	'https://copy.com/aAVFL3LYUx6F2uMO',
        	'https://copy.com/oHKSOkyB6ECObAAc',
        	'https://copy.com/VZCwVBIhZ93DDLed',
        	'https://copy.com/VL7bCBMZnFYQIuhT',
        	'https://copy.com/4TiQnGcqydYTHXeV',
        	'https://copy.com/IBkKdXAmGwJiYAfi',
        	'https://copy.com/XnlyyJwXQFMhh98c',
        	'https://copy.com/VPlpo8p79FMjJGwe',
        	'https://copy.com/An43shtwRVpkBYbm',
        	'https://copy.com/SoPnC2a0FVNuR6RF',
        	'https://copy.com/QmSQRvZs1nx71QtK',
        	'https://copy.com/EMDszGNsitcBBSqE',
        	'https://copy.com/LR7CVEEQHSZtuayn',
        	'https://copy.com/Eo8hnDbhCBrBz0An',
        	'https://copy.com/AiTpwcblfygrcmVw',
        	'https://copy.com/Q69MHzcALeGvskSV',
        	'https://copy.com/3A9CK18OjYRPUrn1',
        	'https://copy.com/471Tn83619yyeWTm',
        	'https://copy.com/mChNBWwFBR3Exp1O',
        	'https://copy.com/B7WN6Cf8rKe6at7e',
        	'https://copy.com/MCwGYdeGfpjuOm9D',
        	'https://copy.com/89dKbv44L1OBqLxD',
        	'https://copy.com/RD9rNW8YUC7SgWGk',
        	'https://copy.com/94T9EdApeoBQKBMI',
        	'https://copy.com/BOCVBuV3P9Noovnr',
        	'https://copy.com/4Cdc4U2Ky2eZHS6s',
        	'https://copy.com/pW8hdEOgsAbppAoV',
        	'https://copy.com/Kjh0XrfEBFcfYRsW',
        	'https://copy.com/wFsZRciP9XLuRMwW',
        	'https://copy.com/j322SvrrKHys3Yzo',
        ]
      },
      // 13
      {
        lat: 13.756331,
        lng: 100.501765,
        thumbnailUrl:'https://copy.com/CqCUOaC3Q7CX4tU8',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Bangkok1',
        contentUrl : [
          'https://copy.com/HWeBMzcpzsv1DM6L',
        	'https://copy.com/dwvFME6Q7YY9ztoX',
        	'https://copy.com/4qR9Jm4nOgi8LToa',
        	'https://copy.com/F3vgSbHqEScUhtPQ',
        	'https://copy.com/32Co3sJlLqGKZL0K',
        	'https://copy.com/nBSfjU8Fh2QPNOD1',
        	'https://copy.com/zv2TUpyodod7B6tt',
        	'https://copy.com/zN94k6fAs390revz',
        	'https://copy.com/K0AAwL2Qkp9QtpJK',
        	'https://copy.com/BLEjpBfFhOSAsUv8',
        	'https://copy.com/uNTxZ9DXTbMLBCbD',
        	'https://copy.com/CqCUOaC3Q7CX4tU8',
        	'https://copy.com/IPEel2LPWzhqCRYV',
        	'https://copy.com/uvCr8apH8HDBLjIp',
        	'https://copy.com/CBYqBKYTcyBLJ4wk',
        ]
      },
      // 14
      {
        lat: 31.196173,
        lng: 121.506042,
        thumbnailUrl:'https://copy.com/pJyCwD3oaXbPtzCy',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Shanghai2',
        contentUrl : [
          'https://copy.com/IWdys4BmW8ApQ3Kh',
        	'https://copy.com/pJyCwD3oaXbPtzCy',
        	'https://copy.com/DV2zgblE4pSxGrKO',
        	'https://copy.com/BEknYmTo9gOnmnOt',
        	'https://copy.com/MR2MG3t0tVpKbREf',
        	'https://copy.com/rS7ivARF7a9ArE3M',
        	'https://copy.com/IFhZjU1NURumi7Hc',
        	'https://copy.com/QKP3HyEo4CEPdkV7',
        	'https://copy.com/EtY90FKHAj64y1y2',
        	'https://copy.com/9k7wJegEhqnwyubJ',
        ]
      },
      // 15
      {
        lat: 41.226232,
        lng: 16.502666,
        thumbnailUrl:'https://copy.com/xrE9463f8289Nubf',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'IronShirt',
        contentUrl : [
          'https://copy.com/xrE9463f8289Nubf',
        	'https://copy.com/MGlFQlG4ghYoSonp',
        	'https://copy.com/RRDPKWRgBQHGdhVM',
        	'https://copy.com/n098H3GkfPTOFKrl',
        	'https://copy.com/kvTSOB9myjbPxI7H',
        	'https://copy.com/AT7F46dCNdw0fl7t',
        	'https://copy.com/2ha8hXY7L3fLGeyg',
        	'https://copy.com/efn9YdjVdsyEiAz3',
        	'https://copy.com/FNYiPTuIXWeo98xW',
        	'https://copy.com/nQtFxUHujIeTzbZu',
        	'https://copy.com/1ouGAIhRi4fXNBEu',
        	'https://copy.com/Z21V34EoNg6BQROE',
        	'https://copy.com/FyZNYk1Z98N0QYEi',
        	'https://copy.com/gLlEY0X9Vnyl3IOK',
        	'https://copy.com/obpRaTooBZYnpCwH',
        	'https://copy.com/4HVDIXcn0uDjnWsH',
        	'https://copy.com/l0JYqSVEerBEehjW',
        	'https://copy.com/xgopOn4M8lC1fSwX',
        	'https://copy.com/0QTiQ8Gyu4HOLHiO',
        	'https://copy.com/HecV3pqgeZcxHb9J',
        	'https://copy.com/2WTEczym1EMfDMlV',
        	'https://copy.com/rJF1Dp7w6gnMRkna',
        	'https://copy.com/l0rdiiEF6mYNzdLI',
        	'https://copy.com/ivMsAbYQ0MobRBf4',
        	'https://copy.com/40Jwu8mkvyN1UsvM',
        	'https://copy.com/I1SAEsxvtPBvf978',
        	'https://copy.com/irbMmSGdKkZ2xjzQ',
        	'https://copy.com/rPldn4tKoCOwvsP8',
        	'https://copy.com/tjiHk9IKQ6N94USa',
        	'https://copy.com/UCdjuqDWpldxGpdZ',
        	'https://copy.com/JVIDOXyHoPzqHlnY',
        	'https://copy.com/DjrDTDXpGKPbKWUU',
        	'https://copy.com/szSmUCiUC3zbu0AG',
        	'https://copy.com/ltwUVO1bDEbFPvl3',
        	'https://copy.com/ANNQ8woQpeg2wCNY',
        ]
      },
      // 16
      {
        lat: 23.129110,
        lng: 113.264385,
        thumbnailUrl:'https://copy.com/gsLoFcqYlnoatgwg',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'GuangZhou1',
        contentUrl : [
          'https://copy.com/QYynm2qNE4OUJQFP',
        	'https://copy.com/gsLoFcqYlnoatgwg',
        	'https://copy.com/ch71Y3Vti8vgIZ2f',
        	'https://copy.com/ymUuPbG7NctTQEL1',
        	'https://copy.com/zDcUO3BXf0IM4WMr',
        	'https://copy.com/RE6Y8Z1abGPyl7uB',
        	'https://copy.com/Zy6abL09lwzbWwiV',
        	'https://copy.com/V7MgtO9WIjJPQ7ac',
        	'https://copy.com/qodJr9uoRMKCpOfr',
        	'https://copy.com/mofZYrXpTEcj4eSS',
        	'https://copy.com/oeHuo1gJgHAoOWqu',
        	'https://copy.com/2nfND9ZVwbeV1xSK',
        	'https://copy.com/dWIEzOTSBUqNGQa2',
        	'https://copy.com/1TUzSxRjW2YTVx6S',
        	'https://copy.com/HUWMuM0ZTmJsijV8',
        	'https://copy.com/nUIoSgFmgR9qNz3b',
        	'https://copy.com/0SRwk2B84vZop3dT',
        	'https://copy.com/EVFcmTX8Y0UTpQHT',
        	'https://copy.com/K0yjE7rivTX1bqKB',
        	'https://copy.com/8Ta6SfSB73hGQ12S',
        	'https://copy.com/Gq0HeWK6k6wVE7zW',
        	'https://copy.com/DM6gVWYoNxhelkd4',
        	'https://copy.com/vmve4fo4sjdJajWz',
        	'https://copy.com/ZLfEtobGGlvF2Qna',
        	'https://copy.com/9PhCwQtWrbSbXnUl',
        	'https://copy.com/icO6lne4pkqm7Vcf',
        	'https://copy.com/eQqHa3suJSg4gxGA',
        	'https://copy.com/dXo3oEURH9pFS7mQ',
        	'https://copy.com/4oT1NvhOAy4g1Rdt',
        ]
      },
      // 17
      {
        lat: 30.274085,
        lng: 120.155070,
        thumbnailUrl:'https://copy.com/Fixv6mo6JSnlUM2v',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'HangZhou1',
        contentUrl : [
          'https://copy.com/Aulp6Was6BVCf3er',
        	'https://copy.com/QAVAoWonVAne9I79',
        	'https://copy.com/HrNMN6e4SGueliVp',
        	'https://copy.com/Fixv6mo6JSnlUM2v',
        	'https://copy.com/dmpfDscXX6iKvkhN',
        	'https://copy.com/QFMHJG0NfAX4AErs',
        	'https://copy.com/J6Czwsb7EOKOctYY',
        	'https://copy.com/dOr9hGUGvbNxu9XC',
        	'https://copy.com/zT3fXKs0HRxjTCKN',
        	'https://copy.com/wAxVQbb3ZBV8Av4d',
        	'https://copy.com/UKxxzECq1PlleB0v',
        	'https://copy.com/4ILCU16SKg2XO1wI',
        	'https://copy.com/fQziXWvyNcN0acw1',
        	'https://copy.com/t41tYCc21mjZHQbH',
        	'https://copy.com/a2ctGPMb3siYYOhM',
        	'https://copy.com/uJ14gnY6dkpFa0fn',
        	'https://copy.com/X8EN1CWx8DC1L6XS',
        	'https://copy.com/Fmu2CjZSOhYT11oK',
        	'https://copy.com/HltLIfXMBY0l4xqn',
        	'https://copy.com/bLYPALoBmzmztJy8',
        	'https://copy.com/HPjWFYdYTa6J6jaR',
        	'https://copy.com/XUwxs7IkYPqnYAxX',
        	'https://copy.com/AkDG1GwwrDCEAPFv',
        	'https://copy.com/Rf1ErN4Ar7tTStGI',
        	'https://copy.com/f2bmNzUhETdtiVAi',
        	'https://copy.com/c4OJ2OZCLhUX9c4H',
        	'https://copy.com/HhqjlYVSt1q0zCkC',
        	'https://copy.com/Mh0E0S2qM2fHTBEZ',
        	'https://copy.com/bOQRhAwmXeA02YJb',
        	'https://copy.com/VOUlaMYMzVxoh3XF',
        	'https://copy.com/va2NfMD6QM4fULwu',
        	'https://copy.com/xRKd3qd9l3DI4BCp',
        	'https://copy.com/0YcysGPKlvlX9tx8',
        	'https://copy.com/kdbkb7VCcBdzdpNR',
        	'https://copy.com/SI02ws1lZZ4DiOqN',
        	'https://copy.com/6oAJibW3K94GRvXy',
        	'https://copy.com/3lcdxmUxavwLC4r7',
        	'https://copy.com/VWZ79ibBhNo8Sd4d',
        	'https://copy.com/4k6Pl4pdIGnvkiVj',
        ]
      },
      // 18
      {
        lat: 18.794790,
        lng: 98.952827,
        thumbnailUrl:'https://copy.com/ZwtgRthisSZxTYK8',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'PoliceTraining1',
        contentUrl : [
          'https://copy.com/ZwtgRthisSZxTYK8',
        	'https://copy.com/nuRySjWj90Pxwtry',
        	'https://copy.com/CtciqosMvyL4gSd9',
        	'https://copy.com/Gd7npW7brLp0oPCh',
        	'https://copy.com/seLMR2xofy4gLYYA',
        	'https://copy.com/YTEfpVYU0HFicKrD',
        	'https://copy.com/ZsefMRNBoVs1yA9q',
        	'https://copy.com/jISbM14FZ37GE9UG',
        	'https://copy.com/8V4oikfJCPTvUIRS',
        	'https://copy.com/hxcoSB94rqZLpTiL',
        	'https://copy.com/IMuHfCLazQHIi9Uh',
        	'https://copy.com/d983wBlZ71HAvLHA',
        	'https://copy.com/Yy89o7T9AaTlCWSR',
        	'https://copy.com/Usq2iCVlY6meo6wj',
        	'https://copy.com/yVbOFoAoM9Lc4x2f',
        	'https://copy.com/uAsEfbKpU6jkpJ6k',
        	'https://copy.com/KdFMIB82jB3dz88A',
        	'https://copy.com/pLMpMADlUjg2XTdj',
        	'https://copy.com/9L0V8fnitcKMOwrh',
        	'https://copy.com/ZSfi4pmfywvf6Yjk',
        	'https://copy.com/cvM6TdSWXbzMnnKW',
        	'https://copy.com/Hg0PR3NDgjq4pA9A',
        	'https://copy.com/rgLzsDMzKer0x9PY',
        	'https://copy.com/ydTt8PItNKjcojns',
        	'https://copy.com/KUznQcKDuxX9xlMd',
        	'https://copy.com/XcyOZXfvrZzlybPG',
        	'https://copy.com/UZjmNN8rQ803zEQo',
        	'https://copy.com/WrEAKz8gg9bvDUXt',
        	'https://copy.com/kY2mg4Y7L9nGtuKg',
        	'https://copy.com/DpZZJLkD8MNbqY3a',
        	'https://copy.com/qqeA3YQi1sBdiMde',
        	'https://copy.com/q8rPFzUApelX87rJ',
        	'https://copy.com/Sr4DrVhhuRCyXW6M',
        ]
      },
      // 19
      {
        lat: 18.746002,
        lng: 99.062347,
        thumbnailUrl:'https://copy.com/gAhMWE7DEhiLi6m3',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'PoliceTraining2',
        contentUrl : [
          'https://copy.com/gAhMWE7DEhiLi6m3',
        	'https://copy.com/0Oh1qUwqKdVodk2R',
        	'https://copy.com/bM2OZQNfO8yrKQnI',
        	'https://copy.com/HLCJ3WrbJhvALUBa',
        	'https://copy.com/tplYcbPNRHvS7tp7',
        	'https://copy.com/D7Itc84sprvdzCno',
        	'https://copy.com/xsal7w3PwlqfhxBM',
        	'https://copy.com/q2Xb4LuNHo4I9A9G',
        	'https://copy.com/QVrQTReA17qHBArN',
        	'https://copy.com/w93LXsgTpG3r3COE',
        	'https://copy.com/DobMorA9b2YZ2rE0',
        	'https://copy.com/VtXFSpPnrmpKhfDQ',
        	'https://copy.com/8a6gHbchbLbPSjqz',
        	'https://copy.com/lIJNHpOlKcbrMeHx',
        ]
      },
      // 20
      {
        lat: 18.506552,
        lng: 98.946304,
        thumbnailUrl:'https://copy.com/0Yz66GEvg0HpqSFt',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Thailand-TG4',
        contentUrl : [
          'https://copy.com/nlDb0WgFn4QnUr6j',
        	'https://copy.com/Rw7pEqE68qBhzKFC',
        	'https://copy.com/u8vLcUJzaPt9MjNd',
        	'https://copy.com/SGedj0wIqWv6Wm1P',
        	'https://copy.com/6QU6g9eyKWgzPKJw',
        	'https://copy.com/fsLAV4KJcdWTUxR9',
        	'https://copy.com/WYL9hPbW0etfp6pd',
        	'https://copy.com/0Yz66GEvg0HpqSFt',
        	'https://copy.com/yWtGeMDFnBCEYHuI',
        	'https://copy.com/gLmGt2CuI8mmblRy',
        	'https://copy.com/4CkxgS0OyAmjoqPA',
        	'https://copy.com/rMmeJJBIsmnm7h2N',
        	'https://copy.com/4IBQsbo2TROS9c1i',
        	'https://copy.com/ar8mBaYDIJf0Upwo',
        	'https://copy.com/RT4HPITPteCZQfgN',
        	'https://copy.com/eocSGxXRhA9qdySK',
        	'https://copy.com/lSD3veP2LrUDrlec',
        	'https://copy.com/yWgwdZr802Sbycbb',
        	'https://copy.com/m8bZqEkxVzR87fZW',
        	'https://copy.com/mCAJwkXhI0pKjCBP',
        	'https://copy.com/ZpMvmjBe1jatijej',
        	'https://copy.com/Ou9jtJxTc1p6LXQh',
        	'https://copy.com/4tVkjY4KcDrFnCB9',
        	'https://copy.com/kqEGEH2v9pz0uJlu',
        	'https://copy.com/V8XwEKcAVBWIuXjt',
        	'https://copy.com/HFI0pzBDzAEZhDo3',
        ]
      },
      // 21
      {
        lat: 34.721685,
        lng: 113.648415,
        thumbnailUrl:'https://copy.com/fksbBeB2IZsVHcdZ',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'ZhengZhou1',
        contentUrl : [
          'https://copy.com/P0so3rxKye7kmKFy',
        	'https://copy.com/RiWZygYx3DBcWcEd',
        	'https://copy.com/fksbBeB2IZsVHcdZ',
        	'https://copy.com/6AaOmoIvxCH8UjUh',
        	'https://copy.com/E4hPxB9p1XIh16JY',
        	'https://copy.com/Pi7LvQeGDG0F0wAA',
        	'https://copy.com/8ui6Kq4VrquW1hFI',
        	'https://copy.com/QXAbztEiCPQhsByS',
        	'https://copy.com/UOLG711TU9qtMSOP',
        	'https://copy.com/KljImCuKnnjUFuDN',
        	'https://copy.com/12dsgCogMKUoHXDa',
        	'https://copy.com/3QAGoIosEAdaMDo8',
        	'https://copy.com/LDeKEhUiwkc0KGlC',
        	'https://copy.com/Ht1KHrsgfes1pWs9',
        	'https://copy.com/Koy34Bp6tB4EOHpU',
        	'https://copy.com/MB270oCQWXZAEXbt',
        	'https://copy.com/uXkjx00fJZeeTzPn',
        	'https://copy.com/nj4nBpbMzzEqEehJ',
        	'https://copy.com/d1Shg0MiyzDBhpJP',
        	'https://copy.com/KuCZoPh1mNEUsHIB',
        	'https://copy.com/4hGgBlxhHvCOOW8I',
        	'https://copy.com/tdHtrvl88YaitQOn',
        	'https://copy.com/mWVxy7UWsOR4BSdg',
        	'https://copy.com/njTAPrx4prU7xIWx',
        	'https://copy.com/wVFl3WIkrJAQNQIo',
        	'https://copy.com/lLjSnm2Yk80dzYjS',
        	'https://copy.com/GkA7mI6O1OXDju0i',
        	'https://copy.com/SFratXBAbHUCDTof',
        	'https://copy.com/YLlFmHfU2gPfzf36',
        	'https://copy.com/b7QYIIvRibreilpH',
        	'https://copy.com/tUobyAXEvRjDOu92',
        	'https://copy.com/uJjeoesfa1Lhi9i2',
        	'https://copy.com/vYaBoHsEfPruWSjq',
        	'https://copy.com/aUExUwfeRGtH2G7e',
        	'https://copy.com/G7y3BUUtGTYoPHLd',
        	'https://copy.com/YiJaOqYFjoRHRama',
        	'https://copy.com/KcuXYNLJ761AVZ2B',
        	'https://copy.com/AKhZp2naD76waitY',
        	'https://copy.com/ACgnXbp2lMELpjXC',
        	'https://copy.com/BM1HZPRWkIc3hHCq',
        	'https://copy.com/CFLBYS6DLQZnbTsS',
        	'https://copy.com/ncUnxdu2tOFWLyW3',
        	'https://copy.com/VteGk0Rol7YIxVDX',
        	'https://copy.com/IPRqHMeatDcNfILn',
        	'https://copy.com/1HtcxoOwzYYogiLE',
        	'https://copy.com/peS8PaSeWLw2oqlP',
        ]
      },
      // 22
      {
        lat: 13.823680,
        lng: 100.573875,
        thumbnailUrl:'https://copy.com/vltkZ2Yvbgh88GN3',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Bangkok2',
        contentUrl : [
          'https://copy.com/vltkZ2Yvbgh88GN3',
        	'https://copy.com/SnNMxO4U6dZkADLn',
        	'https://copy.com/AyRO6SFZsYcO0X9O',
        	'https://copy.com/SD86n2zOs6CFaKyB',
        	'https://copy.com/AYNlUQc6iFHv4OnI',
        	'https://copy.com/HAO88KZaEXBDUVXk',
        	'https://copy.com/ss1a9MJQNFVSYpgc',
        	'https://copy.com/aOBToVGwdFYOsv8A',
        	'https://copy.com/ebLaUYIOMLtVECbB',
        	'https://copy.com/4b4rCBe8Jcq4clLW',
        	'https://copy.com/zKekvnwgVWZwvoFV',
        	'https://copy.com/yi6HvoBclgua0pdi',
        	'https://copy.com/dpPN9tKOHwsAcXkZ',
        	'https://copy.com/xKC19Gr6BJymQoLp',
        	'https://copy.com/8rJr76XXUh61TaGZ',
        	'https://copy.com/cllvMFbDgynwRKfk',
        	'https://copy.com/yFKf90oI0dIQi9fr',
        	'https://copy.com/82EvdtF4QkVsqBIZ',
        	'https://copy.com/9939hQvSgQ4XkL3D',
        	'https://copy.com/T0Bl7L4xAjY940x3',
        	'https://copy.com/RZleiYeeILN214Qk',
        	'https://copy.com/FLm2FJgfN16Iy0A4',
        	'https://copy.com/1q7V7Iavmq2Uernr',
        	'https://copy.com/TpQFxYeHfTjVhvcO',
        	'https://copy.com/N3QljyGD4FuvSl4z',
        ]
      },
      // 23
      {
        lat: 23.045115,
        lng: 113.295592,
        thumbnailUrl:'https://copy.com/0WpMz4jCAtYmQ71m',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'GuangZhou2',
        contentUrl : [
          'https://copy.com/Zgfhkikxjn3iEFrp',
        	'https://copy.com/H2zxzI3EmiutaN3g',
        	'https://copy.com/D4iUJURyP6kfdUIF',
        	'https://copy.com/gZ7r3BgefPBeinWM',
        	'https://copy.com/fVqc4FnlCOmbaEWL',
        	'https://copy.com/hqZumyxTp7oFwn9x',
        	'https://copy.com/NpMsMTpwkXVuflms',
        	'https://copy.com/1D4fnxP89wluol9N',
        	'https://copy.com/QOnnlA1pbRv6urHe',
        	'https://copy.com/BrdYiFYKYlUt6fZQ',
        	'https://copy.com/zMeEVYor7fNsT6Vn',
        	'https://copy.com/u71PIIwxyAef2vAl',
        	'https://copy.com/MhjjTgSxfy3LNFDP',
        	'https://copy.com/XmeLYLQnOcVcWReO',
        	'https://copy.com/0WpMz4jCAtYmQ71m',
        	'https://copy.com/0BfbZJOmQxxhRXY9',
        	'https://copy.com/7wdGKNHOO2237Dik',
        	'https://copy.com/XKQJ8TfetGEwWJwO',
        	'https://copy.com/3DX8yIexsMfc1fZg',
        	'https://copy.com/MxAwnBjzEI8w7ECP',
        	'https://copy.com/rixej3BfQqkPkPPj',
        	'https://copy.com/uzoDTtPc4bKfMt9M',
        	'https://copy.com/Yc7k4OtcLtUV1JaA',
        	'https://copy.com/2FZHmO9ue2XNrroF',
        	'https://copy.com/muOxd6JghTfNv1oT',
        	'https://copy.com/jfy1pTfSsGyMsfBt',
        	'https://copy.com/FQUxNbcskaQjszf4',
        	'https://copy.com/HxnCUsmi3Cp3aUSI',
        	'https://copy.com/pkuEmLJBe9GOsNMo',
        	'https://copy.com/0TNLkIdBK98DqkaW',
        	'https://copy.com/R4kQ8BHAhylGyLz0',
        	'https://copy.com/RoDvshEtDZeF2jMd',
        	'https://copy.com/m9rXr074zZ1FXOn2',
        	'https://copy.com/0uKxlaJBYfkuj7T1',
        	'https://copy.com/Gy92VKFfYLJKQoaJ',
        	'https://copy.com/wu6Cz1qsC9lz3aQb',
        	'https://copy.com/aqiQboLEXdc9Pezg',
        	'https://copy.com/xyCaykd9myB21RRn',
        	'https://copy.com/cIkdpH7D7AKnjYSi',
        	'https://copy.com/vnemum28l0jM2myN',
        	'https://copy.com/Lax1dbSfk67YU1QT',
        	'https://copy.com/htgC1840A4rOMyzg',
        	'https://copy.com/bTmBohnR3HOXef01',
        	'https://copy.com/rhiWTquPshCVIbhd',
        	'https://copy.com/UGOSI4Q8AnZiXtgB',
        	'https://copy.com/4aKFX7OTYov7rbqv',
        	'https://copy.com/i9kqnf0auxn0pxY0',
        ]
      },
      // 24
      {
        lat: 41.210527,
        lng: 16.575623,
        thumbnailUrl:'https://copy.com/2wIyNHHmThEKUMC7',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'TaiChi1',
        contentUrl : [
          'https://copy.com/HgTtnyAN4WirZkDP',
        	'https://copy.com/trTY9htroVpQrNdP',
        	'https://copy.com/BIiJYw8kJm2xFKs0',
        	'https://copy.com/oaL0WMgKVTm8VkGg',
        	'https://copy.com/soyFLbTVtYd49VJB',
        	'https://copy.com/9ezL2Dh2DUfzgTOa',
        	'https://copy.com/qM7ymKCRQHRbYTDH',
        	'https://copy.com/o0110bAJ3xyQlEjG',
        	'https://copy.com/4bnfsvfcXMc9AHu1',
        	'https://copy.com/MW6UvQDEWZre0nYt',
        	'https://copy.com/PpreWt3Pi0K3fPId',
        	'https://copy.com/g6tZSt903c8imZib',
        	'https://copy.com/chw2QOX8fyqUKX3U',
        	'https://copy.com/HPNJSdQ7eO9O9Xqe',
        	'https://copy.com/a7b6G2WXqmGKKlIq',
        	'https://copy.com/DJMhqPI7uovYCBu6',
        	'https://copy.com/2wIyNHHmThEKUMC7',
        	'https://copy.com/8w2l2RdZwI8uRXfs',
        	'https://copy.com/2YV7N9EqCRKXszIT',
        	'https://copy.com/IMolY9iDRsgAmy13',
        	'https://copy.com/y3bOheZjoOeBw0Wt',
        	'https://copy.com/2jQzQxw4afRsAZcE',
        	'https://copy.com/sFtpXY8COVP44DfH',
        	'https://copy.com/aEQ3r7H0wEzfvkgK',
        	'https://copy.com/yBehdDL2IQvHIVvO',
        	'https://copy.com/ErZHTSPzLsPwR3C0',
        	'https://copy.com/4rdWKsWZEKiJF6nV',
        	'https://copy.com/oCqEDd1RhDFmwXob',
        	'https://copy.com/cLorHJhhHeckgSCG',
        	'https://copy.com/AyJjNhIoJCRzGhGO',
        	'https://copy.com/InICVT0TLuIiPwFn',
        	'https://copy.com/z2J7dUKnzTaIfI7g',
        	'https://copy.com/NWKl1Nw8wYFek30L',
        	'https://copy.com/Zwd8Ap6PLgXku13y',
        	'https://copy.com/CJ2Dx0DH6BDd6jPr',
        	'https://copy.com/j3rqoTz1bzlc0a7z',
        	'https://copy.com/gUUgUi4mHevoRah9',
        	'https://copy.com/07bAB2iXE3a7PQCX',
        	'https://copy.com/7euJ3Qgj37datB0F',
        	'https://copy.com/zUs8eUlkFay73cO9',
        	'https://copy.com/IbWu4tKmerO9Fz7y',
        	'https://copy.com/C1bP1i10QsZeqcX8',
        	'https://copy.com/NgyQ9lw9PChKC0jI',
        	'https://copy.com/P0pBWUePRDmvv1nP',
        	'https://copy.com/PZqp7o8A0774tPjM',
        	'https://copy.com/TbP7No0Prd9gvCRc',
        	'https://copy.com/7j3s2lmrUum4fUJI',
        	'https://copy.com/tnPwjaNFAI2tXKMk',
        	'https://copy.com/LiRKd3dtmsfDDHSO',
        	'https://copy.com/NkBsH3Eu7dsERNFC',
        	'https://copy.com/Acd8pIJCIvZrNCuu',
        	'https://copy.com/XVP9ytysiZqCIhM1',
        	'https://copy.com/TdOOcfk8NUnzeOr7',
        	'https://copy.com/8zRuBw99stEpaAcg',
        	'https://copy.com/QTIgrfGq8WS2ZxTk',
        	'https://copy.com/ZQN7m89J3JG9noRf',
        ]
      },
      // 25
      {
        lat: 44.426348,
        lng: 26.104202,
        thumbnailUrl:'https://copy.com/3kKZuEKMu6CsyDZp',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Romania1',
        contentUrl : [
          'https://copy.com/YAU0nK0c20sW9PvK',
        	'https://copy.com/fxh0sObfS4oQq91c',
        	'https://copy.com/ko7v7Z2jCXlP9fC6',
        	'https://copy.com/3kKZuEKMu6CsyDZp',
        	'https://copy.com/1xcvqEguzB0vIzcR',
        	'https://copy.com/lw8lss1tDAcFgZjV',
        	'https://copy.com/xmavxHEOJO2CTfmW',
        	'https://copy.com/mEmcJyVis7VMCflj',
        	'https://copy.com/pAjP3ApC7PGwhQ2f',
        	'https://copy.com/YD7hjBJYEVKvT8c8',
        	'https://copy.com/X8syf7LC8rTIlyjg',
        	'https://copy.com/c3KsTuOnfOaVLIbg',
        	'https://copy.com/tsQMS7zcechLhJlO',
        	'https://copy.com/hxXk2e22QFeSSkDo',
        	'https://copy.com/fsAjpjrE0RwQs7uI',
        	'https://copy.com/W92pRPrCsij6lyvu',
        	'https://copy.com/xtbBH32hsieWYCJe',
        	'https://copy.com/z2elW6XWzoxySCdu',
        	'https://copy.com/Vy1lcYqjtqe94zAi',
        	'https://copy.com/pMFvSymNcQnn8sfC',
        	'https://copy.com/bmwy31N7eTkhjQgg',
        	'https://copy.com/P9fcnRJAejppvBSb',
        	'https://copy.com/JbKoImDliM8ohar2',
        	'https://copy.com/PASsVfKknyA6CxtA',
        	'https://copy.com/y7asXpaGSVTCYX7w',
        	'https://copy.com/7DOgNUmEQNmjD6dT',
        	'https://copy.com/s2tOUnHgLhMyvzCK',
        	'https://copy.com/UOMrf6iOmnliwsrY',
        	'https://copy.com/g6KBUQ2MaCiYPNdu',
        	'https://copy.com/tEUhBuOIIb1j7VqG',
        	'https://copy.com/Zv0PGmxgKk4mHM2t',
        	'https://copy.com/8XpskD1RF4OQxtdL',
        	'https://copy.com/Ldck2WXSoKkcoAsD',
        	'https://copy.com/KLeTDwXU0fOHdHQK',
        	'https://copy.com/k4taCAfWNWt9tUCF',
        	'https://copy.com/2UKfwatSE9rUtUKL',
        	'https://copy.com/NFlAdQpIflEhowp6',
        	'https://copy.com/KLm8Fdc4TzY4Sj4e',
        	'https://copy.com/xtfVIVkbBnsvED4k',
        	'https://copy.com/GT80avmvheXseFo2',
        	'https://copy.com/JTOagOTuwo07GUXA',
        	'https://copy.com/xUDZIrxjCMw1M2S7',
        	'https://copy.com/xpyswCKOo2pRcRf4',
        	'https://copy.com/ZLSAtgo3W9dfjtTZ',
        	'https://copy.com/ZW137oq1n7hAsxsT',
        	'https://copy.com/UdWr9xqYc9mWubM7',
        ]
      },
      // 26
      {
        lat: 36.895599,
        lng: 30.715370,
        thumbnailUrl:'https://copy.com/Hr9AWHN8NTyyIH6v',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Turkey1',
        contentUrl : [
          'https://copy.com/Hr9AWHN8NTyyIH6v',
        	'https://copy.com/gdz1ccN2NOuDspJr',
        	'https://copy.com/yGRyR9EsJcIhNvep',
        	'https://copy.com/HFYswTLXBf1J8ULW',
        	'https://copy.com/BPjHPYzyCSJWLgIU',
        	'https://copy.com/IrqOLpi37z8zPH1C',
        	'https://copy.com/m0HUXfkH6RTbF7RP',
        	'https://copy.com/p9zVTR6yLFQbkitB',
        	'https://copy.com/ZXW0PA6gtNr8aWrO',
        	'https://copy.com/D6lgxOJLOmhzhpdI',
        ]
      },
      // 27
      {
        lat: 41.212432,
        lng: 16.435547,
        thumbnailUrl:'https://copy.com/z7x9bbDss8DTtk8I',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Italy3',
        contentUrl : [
          'https://copy.com/z7x9bbDss8DTtk8I',
        	'https://copy.com/p0L0chGS2pXBBDb0',
        	'https://copy.com/QSKZhXAmjdorb8JG',
        	'https://copy.com/wV6pLduz3O0RPMz7',
        	'https://copy.com/Suh1GPQaJyRB0qT2',
        	'https://copy.com/RpwIhV8MfvEr2L3U',
        	'https://copy.com/cJdlHSqdzFXyUnbC',
        	'https://copy.com/4cnu71lPHYfF4V4y',
        	'https://copy.com/cJdlHSqdzFXyUnbC',
        	'https://copy.com/4cnu71lPHYfF4V4y',
        	'https://copy.com/ODWNy3kXo8LCHGjA',
        	'https://copy.com/VsWIj6EkgbCzVOD2',
        	'https://copy.com/FKWlNfrjnGJiMlBr',
        	'https://copy.com/TWVM8E3rOHkUBYgu',
        	'https://copy.com/dm6Q2mubbMQ1KYVB',
        	'https://copy.com/MGrL6JOxcEIeQ0KB',
        	'https://copy.com/cOCGsrhHW4iCB8OB',
        	'https://copy.com/ZZReCWiJlScJWxkr',
        	'https://copy.com/dtjkf3lwE9dBtsLc',
        	'https://copy.com/kBIbAIlFmjMv9C89',
        	'https://copy.com/uUnwYSrnu0OAMmqk',
        	'https://copy.com/ryFpbiPa0EK4qvVS',
        	'https://copy.com/KHRoql8QUXpgzKPR',
        	'https://copy.com/SG0kWVsRyW4rpaWB',
        	'https://copy.com/ob2iyjVZmwxxNoUM',
        	'https://copy.com/YjzIHBhYG3rIhoHZ',
        	'https://copy.com/DQueFxUO2Dmo3sxd',
        	'https://copy.com/CayKGYGkXZHU0Dl0',
        	'https://copy.com/rAyvgEKZQD0VMy0r',
        	'https://copy.com/drcKcoB0THsrk9y4',
        	'https://copy.com/vjSvkO1xaf1obq83',
        	'https://copy.com/vjSvkO1xaf1obq83',
        	'https://copy.com/HNUkOLcyciBLb9LH',
        	'https://copy.com/wGMUYwfsbyexIcwp',
        ]
      },
      // 28
      {
        lat: 41.158689,
        lng: 16.495972,
        thumbnailUrl:'https://copy.com/jaHDsmeupmkrnH9k',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'WorkshopBasicItaly',
        contentUrl : [
          'https://copy.com/VZaMh4f2keCIujYs',
        	'https://copy.com/dxZ72AcWhTMOKrOG',
        	'https://copy.com/BSugAyG8qP1WJvkU',
        	'https://copy.com/jaHDsmeupmkrnH9k',
        	'https://copy.com/CbyltwR1iRpLpksO',
        	'https://copy.com/rqReuV7g83wrWep8',
        	'https://copy.com/wdJsU6imGWbuOUOO',
        	'https://copy.com/cnKBuEBlbMEnzHKM',
        	'https://copy.com/4hq4C8MtVTtUSmst',
        	'https://copy.com/004QCsjZVizip1do',
        	'https://copy.com/6eVNXvvxBVDc2WyR',
        	'https://copy.com/kEtvXdG1LfAmTKPD',
        	'https://copy.com/hnCh7TPgDn19R7Lv',
        	'https://copy.com/TfpliUagSguk2ZaU',
        	'https://copy.com/p8ekAtsQ39tebNp0',
        	'https://copy.com/cKyOuXJJnXKPpvuY',
        	'https://copy.com/7wlQ3XPoKAZ8KyUE',
        	'https://copy.com/t8buZsFNtfWXrvPU',
        	'https://copy.com/QuPeV4NzxNOgix0e',
        	'https://copy.com/nDA9NDwvSCr8h3fx',
        	'https://copy.com/cRYTWsDYfBes3h7N',
        	'https://copy.com/HKjnpz4IWiyVr2ls',
        	'https://copy.com/0xFIc9SgDILzdTtC',
        	'https://copy.com/FtxKXxMKVw3L4Do4',
        	'https://copy.com/WW2cwuHATdPuZVGL',
        	'https://copy.com/hQzDtgRd0XJZYlpw',
        	'https://copy.com/mQgCLFpQUyErnSZI',
        	'https://copy.com/OJhSpq42SsFGngYX',
        	'https://copy.com/qHAYeI9rBOV7yo18',
        	'https://copy.com/fioK9033VegyIVX1',
        	'https://copy.com/Ne8qJ62Jj0GC3A2F',
        	'https://copy.com/Em394JolHNlBEF9j',
        	'https://copy.com/zllUCCn87XYJlkvU',
        	'https://copy.com/KztEukfIsGqvvqN7',
        	'https://copy.com/I9GENam1Fzb6kCjn',
        	'https://copy.com/8IrjupOtoWmVTWbJ',
        	'https://copy.com/IIBNVHWug2m3D6XH',
        	'https://copy.com/T9GfMs7HHixchHC6',
        	'https://copy.com/gNR9PfocHAZ2bEUF',
        	'https://copy.com/lY3DL1rdf3V3lzW0',
        	'https://copy.com/omsExBUrL6zraFi9',
        	'https://copy.com/zIfP2ifZSPoa2zDr',
        	'https://copy.com/7eHFbEWJvJAaqsxo',
        	'https://copy.com/ePFDuRNYt6lWmJH3',
        	'https://copy.com/S08qIDI64eLZ1ct9',
        	'https://copy.com/XKOg4qMXYdEn2akR',
        	'https://copy.com/ghkQSeFEhKgDMv4c',
        	'https://copy.com/XOtIdasNsfcX1Cey',
        	'https://copy.com/gLuJ7WOipaF6lfPH',
        	'https://copy.com/YETKCyPrQAuPqW8t',
        	'https://copy.com/9Asv1p4eeiw7OYQD',
        	'https://copy.com/pF9rTM0b6v4BWulw',
        	'https://copy.com/vF24saB6OROBDu0Y',
        	'https://copy.com/KqwHCgGx2iheequc',
        	'https://copy.com/kN0RuvYjDZgXF1QQ',
        	'https://copy.com/RF7We4PcgO6qtslo',
        	'https://copy.com/kIOcNYQgmAezLfSq',
        	'https://copy.com/Wcv7TsuujbgQsHTD',
        	'https://copy.com/BTJTVM7r8sQMFokt',
        	'https://copy.com/BdrY1inFV3o4c43q',
        	'https://copy.com/eoYnBB264VUKwTC7',
        	'https://copy.com/ExwAUijWEMBIvuHg',
        	'https://copy.com/w1mD8umk4k8kVy4q',
        	'https://copy.com/8G00QOvcBOqWy8Pe',
        	'https://copy.com/pZk87pketl194ZUJ',
        	'https://copy.com/KDnxczIrnowH8HJr',
        	'https://copy.com/ipxecAk1Tiv6yr3I',
        	'https://copy.com/zxOfLXiwJCJsu1r1',
        	'https://copy.com/mAbMhtZTV4Ucowq8',
        	'https://copy.com/AXBnbisqEPcmZAgV',
        	'https://copy.com/xC0uYjJHXHy3rq87',
        	'https://copy.com/vKDIfQ8Ylkzl0Jdl',
        	'https://copy.com/mE23txCj34AMsEIF',
        	'https://copy.com/JHT8M7PSLL0s99hM',
        	'https://copy.com/7GWXFTF6PjmoXzMi',
        	'https://copy.com/eG3VBIbU7YyBn31t',
        	'https://copy.com/Kbv2KCdlA1ZlBIDH',
        	'https://copy.com/Ncb1VQEzNxcInlIG',
        	'https://copy.com/TQQ4pnsiwLJmx02x',
        	'https://copy.com/TeUxBjXJk4F8K4Gx',
        	'https://copy.com/2b1ZT3TNRbQnERr4',
        	'https://copy.com/8VZIoMWRDq6vx4Ao',
        	'https://copy.com/3Q4MI23RjYoRacAv',
        	'https://copy.com/7SuTPpKQfO6EXBub',
        	'https://copy.com/fGdXxsUjxcO8zOAA',
        	'https://copy.com/WFf2AiME7AZ7JnIs',
        ]
      },
      // 29
      {
        lat: 41.154553,
        lng: 16.254272,
        thumbnailUrl:'https://copy.com/taUDhysQvD6H7cs3',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Ansel',
        contentUrl : [
          'https://copy.com/taUDhysQvD6H7cs3',
        	'https://copy.com/tlH7GwGW6gwK0GXJ',
        	'https://copy.com/DOQxKMMW6gZvHOdz',
        	'https://copy.com/bFYFiM8crWK0d26T',
        	'https://copy.com/kZBYAJRAI9PbAziB',
        	'https://copy.com/kASRFlZJVK8aOQmH',
        	'https://copy.com/HZkqe3GGoug4G3vB',
        	'https://copy.com/3VNWPr8kOnLebhRK',
        	'https://copy.com/JY2GXtdGDQ3KWUCQ',
        	'https://copy.com/adga9st4gCyZsmY2',
        	'https://copy.com/JQHZQQwF2H2KPe0m',
        	'https://copy.com/97cNsEXucF28vicL',
        ]
      },


      // 30-1
      {
        lat: 46.697405,
        lng: 7.737647,
        thumbnailUrl:'https://copy.com/XptGdOVZMSC1RoEE',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Switzerland1',
        contentUrl : [
          'https://copy.com/hvjmUtJxAsyBCEIi',
        	'https://copy.com/qkyuo3FfB33hP87Z',
        	'https://copy.com/BmleCaeBOtgEABQc',
        	'https://copy.com/PsSdRQANoOuBoboh',
        	'https://copy.com/XptGdOVZMSC1RoEE',
        	'https://copy.com/x2Kv4IzU4HMrYowr',
        	'https://copy.com/TaVEm4yCSojVcMoT',
        	'https://copy.com/xVJYzeQ1H8WvQvBe',
        	'https://copy.com/8u9m9rD4PFAMUsi4',
        	'https://copy.com/Jp8H31wdCJAKP4Ur',
        	'https://copy.com/nQFqFxSjMp46X4AI',
        	'https://copy.com/ANUAZbXWg4qRgoON',
        	'https://copy.com/Xbm02SK3LRLe62AL',
        	'https://copy.com/QB46oN2vmWXje7hq',
        ]
      },
      // 30-2
      {
        lat: 46.679050,
        lng: 7.846470,
        thumbnailUrl:'https://copy.com/G6OpdO4ivq4EoZfr',
        albumWidth: 50,
        albumHeight: 38,
        albumName: 'Switzerland2',
        contentUrl : [
          'https://copy.com/G6OpdO4ivq4EoZfr',
        	'https://copy.com/VGF8dd14LDsQ61jy',
        	'https://copy.com/N6wYbOBpzB0YfgA8',
        	'https://copy.com/DvcMscY8I40tQFGf',
        	'https://copy.com/CR3vl1Vlfm0RB2m4',
        	'https://copy.com/cfQ8qN9HzjdCFuxG',
        	'https://copy.com/DNpDq1xGUFhyxCIa',
        	'https://copy.com/19cVLMhHbhSPfaRR',
        	'https://copy.com/f8RcOEL0SdhTW6Bj',
        	'https://copy.com/ZBfBVhGnnHBI2jSY',
        	'https://copy.com/rvMqbuoehYWdcUwv',
        	'https://copy.com/PkNmTkWRARLDlAgX',
        	'https://copy.com/YVfitYcim39Xfjwu',
        	'https://copy.com/EEL9McSpzXfwDTb4',
        	'https://copy.com/Qoff4Nq4hbiaix8l',
        	'https://copy.com/V2qAGr8NBi6tyWJX',
        	'https://copy.com/pnQ6hR3rr2OnZ79g',
        	'https://copy.com/69fbQ8ToAmwRlnbo',
        ]
      },
    ]
    //insert
    _.each(marker, function (data) {
      Markers.insert(data)
    })
  }
})
